### PR TITLE
fix #185 - report not shown

### LINKED ISSUE #185: report not shown
The report option seems to be broken. Nothing is displayed. Same result with 'min' or 'gzip'.
I'm using version 0.12.2

### PR DESCRIPTION
**Pull request by philippsimon**
Fix issue #185.

After the task is finished a summary like this is logged:
```
>> 84 sourcemaps created.
>> 84 files created.
```

### CODE REVIEW

**Comment by philippsimon** [comment]
does anybody has more experience with Travis?
So how can i let a test run again?
The one build failed as github wasn't reachable for some time (the others passed)
```
The command "eval git clone --depth=50 git://github.com/gruntjs/grunt-contrib-cssmin.git gruntjs/grunt-contrib-cssmin" failed. Retrying, 2 of 3.

Cloning into 'gruntjs/grunt-contrib-cssmin'...
remote: Counting objects: 287, done.
remote: Compressing objects: 100% (158/158), done.
remote: Total 287 (delta 143), reused 246 (delta 109), pack-reused 0
Receiving objects: 100% (287/287), 45.53 KiB | 0 bytes/s, done.
Resolving deltas: 100% (143/143), done.
Checking connectivity... done.
$ cd gruntjs/grunt-contrib-cssmin
384.77s$ git fetch origin +refs/pull/199/merge:
fatal: unable to connect to github.com:
github.com[0: 192.30.252.129]: errno=Connection timed out


The command "eval git fetch origin +refs/pull/199/merge:" failed. Retrying, 2 of 3.

fatal: unable to connect to github.com:
github.com[0: 192.30.252.129]: errno=Connection timed out


The command "eval git fetch origin +refs/pull/199/merge:" failed. Retrying, 3 of 3.

fatal: unable to connect to github.com:
github.com[0: 192.30.252.128]: errno=Connection timed out


The command "eval git fetch origin +refs/pull/199/merge:" failed 3 times.

The command "git fetch origin +refs/pull/199/merge:" failed and exited with 128 during .

Your build has been stopped.
```

**Comment by philippsimon** [comment]
just read the reopening restarts the Travis build, but sadly still the connection to github times out. i'll retry it later.

**Comment by vladikoff** [comment]
Yeah github is under a DDOS right now, so that may be happening

**Comment by XhmikosR** [comment]
@philippsimon: do you plan to do the same for other contrib plugins too?

**Comment by philippsimon** [comment]
@XhmikosR yes sure - if you tell me where it is missing i can fix some

**Comment by XhmikosR** [comment]
Most if not all contrib plug-ins are missing report. I can make a list
later. BTW the size should be reported too. @vladikoff thoughts?

**Comment by philippsimon** [comment]
done - see pull request https://github.com/gruntjs/grunt-contrib-cssmin/pull/200

**Comment by XhmikosR** [comment]
Something doesn't look right in that PR. I'll comment there when I'm back
so please don't merge it yet.

**Pull request merged**
