### PR TITLE
Add maxLineLength functionality [set the compiled file's characters-per-line limit]

### PR DESCRIPTION
**Pull request by seavor**
I really can't believe this feature wasn't already handy :)

(Apologies if implementation is shoddy, first time altering a grunt module and only half knew what i was doing. Feedback is always welcome)

### CODE REVIEW

**Comment by sindresorhus** [comment]
No thanks. That should be implemented in `clean-css` or a separate grunt task.

**Comment by seavor** [comment]
From what I can tell, this is they best they have, which is hardly the same thing. imho, the grunt-task that minifies your css should also be able to restrict how much text can go on a single line. Such things can break some browsers, so seems a shame that no one out here seems interested in supporting it.

    There is a -b/--keep-line-breaks option which will add a break after every selector.

https://github.com/jakubpawlowicz/clean-css/issues/321

**Comment by sindresorhus** [comment]
@seavor This is just a wrapper task of `clean-css`. Any functionality should go into `clean-css`. You're barking up the wrong tree.

**Comment by seavor** [comment]
Not trying to bark up anything lol but point taken. I wasn't aware this was simply a wrapper.

    Options are passed to clean-css. In addition this task defines some extra options:

^Just led me to believe there was room for more. If i find the time tho I'll see about adapting it into clean-css

**Pull request closed without merging**
