### PR TITLE
Bumps clean-css dependency to version 5.

### PR DESCRIPTION
**Pull request by jakubpawlowicz**

### CODE REVIEW

**Comment by jakubpawlowicz** [comment]
clean-css v5 dropped Node.js 6 and 8 support but internally no new lang features are used. Yet the build failed due to chalk using `...` spread operator syntax. 

What should we do?

**Comment by XhmikosR** [comment]
No worries, I'll update the repo later today or tomorrow :)

**Comment by XhmikosR** [comment]
@jakubpawlowicz unfortunately I can't push to your fork's master branch. I rebased and cherry picked the patches manually.

**Comment by jakubpawlowicz** [comment]
Cool, thanks for releasing it as v4.0.0!

**Pull request closed without merging**
