### PR TITLE
Update clean-css to ~4.0.3.

### PR DESCRIPTION
**Pull request by XhmikosR**
**DO NOT MERGE YET**

@vladikoff: things to do before we merge this:

- [x] Update docs with any changed clean-css options
- [ ] Decide if it's going to be a major version bump; I vote yes.

### CODE REVIEW

**Comment by XhmikosR** [comment]
ping @vladikoff

**Comment by XhmikosR** [comment]
@jakubpawlowicz: things seem to work fine, but since you know better are there any API changes in v4?

We basically do https://github.com/gruntjs/grunt-contrib-cssmin/blob/master/tasks/cssmin.js#L44

Otherwise I think we can merge this and release a new version. :)

**Comment by XhmikosR** [comment]
Ping @vladikoff

**Comment by XhmikosR** [comment]
@vladikoff: please npm publish this; I don't have rights for this repo.

**Comment by XhmikosR** [comment]
@vladikoff ^^

**Comment by XhmikosR** [comment]
@vladikoff: ping

**Comment by vladikoff** [comment]
@XhmikosR Done! Sorry for the delay, I added you to npm for this package 👍

**Comment by XhmikosR** [comment]
Thanks!

**Pull request merged**
