### PR TITLE
added saved bytes to report

### PR DESCRIPTION
**Pull request by philippsimon**
see #185

### CODE REVIEW

**Comment by philippsimon** [comment]
it compares the string length before and after applying css-min

**Comment by philippsimon** [comment]
ah yes - i would say we should update the version so the people can load it.

**Comment by XhmikosR** [comment]
You should always squash same patches.

Now regarding this. I don't get it. Why don't you use the same code that's being used a few lines above with `maxmin` and you add a new dependency?

**Comment by philippsimon** [comment]
Yes - i would have done that, but for my first report fix i mainly used some code from grunt-contrib-uglify where they didn't print the size (so i could also add it there).

And I used pretty-bytes (also used in [grunt-contrib-imagemin](https://github.com/gruntjs/grunt-contrib-imagemin/blob/master/tasks/imagemin.js)) as minmax works only with strings and buffers and i didn't want to keep all the uncompressed and compressed css in memory.

I just checked the code of [maxmin](https://github.com/sindresorhus/maxmin) and actually I could also create a pull request so it allows also Numbers as a parameter.
What do you think?

**Comment by philippsimon** [comment]
As it's nearly no work I create a pull request for maxmin. If @sindresorhus accepts it I would only use then maxmin.

**Comment by philippsimon** [comment]
@XhmikosR or @vladikoff can you unmerge my pull request #199?
I will squash then all my commits as soon as i have a response from @sindresorhus about maxmin.

And sorry for all the commits - I'll send from now on only one pull request for a fix.

**Comment by XhmikosR** [comment]
Just revert it in your branch and work on top of it.

**Comment by philippsimon** [comment]
as the `maxmin` dependency didn't update the version if use at the moment the commid id to load the correct dependency. as soon as maxmin has updated the version i will update my commit. as it's no important fix i think before it shouldn't get merged.

**Comment by sindresorhus** [comment]
New maxmin version published. You will also need to fix the merge conflict in this PR.

**Comment by philippsimon** [comment]
as i don't manage to squash my commits please merge it like this
(i guess git rebase doesn't really work as i merge with a remote)

**Comment by XhmikosR** [comment]
`. `git rebase -i upstream/master`
2. Now, choose squash for those 2.
3. `git rebase --continue`.

**Comment by philippsimon** [comment]
I tried that but it doesn't work.
`git rebase -i upstream/master` lists only one commit and so i can't squash. When i use `git rebase -i upstream/master HEAD~2` i just get the message: `noop`

**Comment by XhmikosR** [comment]
Did you fetch upstream before doing any of the above? Works perfectly fine here.

**Pull request closed without merging**
